# A simple pipeline for testing puropses.

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  displayName: 'Build the application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    steps:
    - script: echo "echo 'Hello world!'" > hello.sh
      displayName: 'Build hello world'
      
  - publish: 'hello.sh'
      artifact: drop
