# A simple pipeline for testing puropses.

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build'
  displayName: 'Build the application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'

    steps:
    - script: echo "echo 'Hello world!'" > hello.sh
      displayName: 'Build hello world'
      
    - publish: 'hello.sh'
      artifact: drop

- stage: 'Deploy'
  displayName: 'Deploy the artifact'
  dependsOn: Build
  condition:  succeeded()
  jobs:
  - deployment: Deploy
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
